### ISSUE TITLE
Update Bugzilla end-point for recent Rest API

### ISSUE THREAD

**Issue by whimboo** [AutomatedTester/automation-services-bot#37]
The URL for the Rest URL endpoint will be updated soon. So the code which is used here, will not work in the near future anymore:

https://github.com/AutomatedTester/automation-services-bot/blob/master/bot.js#L102

So the code has to be updated accordingly to the new specs as found here:
https://wiki.mozilla.org/Bugzilla:REST_API

**Comment by edmorley** [comment]
@AutomatedTester, Is this project still in use?

(Context: https://bugzilla.mozilla.org/show_bug.cgi?id=1003236)

**Comment by AutomatedTester** [comment]
@edmorley I think that this is now closed

**Comment by edmorley** [comment]
Do you mean the project is no longer in use, or you think this issue is already fixed?

If the latter, this issue needs to be reopened, since the bot is still using the BzAPI shim (which has performance problems):
https://github.com/AutomatedTester/automation-services-bot/blob/718287a6f0f3243f709689329480bb066bbf351e/bot.js#L102-L107

**Comment by AutomatedTester** [comment]
The bot is off and this project is no longer maintained
